const availableLangs = ["en", "es", "gl", "la"];
const defaultLang = "en";
let lang = defaultLang;
const TR = {
    MOLI: {
        en: "MOLI",
        es: "MOLI",
        gl: "MOLI",
        la: "MOLI",
    },
    WorkInProgress: {
        en: "WORK IN PROGRESS",
        es: "OBRA EN DESARROLLO",
        gl: "OBRA EN DESENVOLVEMENTO",
        la: "WORK IN PROGRESS",
    },
    PressAnyKey: {
        en: "PRESS ANY KEY",
        es: "PRESIONE CUALQUIER TECLA",
        gl: "PREMA CALQUERA TECLA",
        la: "PREMET ILLE CLAVEM",
    },
    PLAY: {
        en: "PLAY",
        es: "JUGAR",
        gl: "XOGAR",
        la: "LUDERE",
    },
    START: {
        en: "START",
        es: "INICIAR",
        gl: "INICIAR",
        la: "INITIARE",
    },
    START_MENU: {
        en: "START MENU",
        es: "MENÚ DE INICIO",
        gl: "MENÚ DE INICIO",
        la: "MENU INITIUM",
    },
    HELP: {
        en: "HELP",
        es: "AYUDA",
        gl: "AXUDA",
        la: "AUXILIUM",
    },
    ABOUT: {
        en: "ABOUT",
        es: "ACERCA DE",
        gl: "SOBRE",
        la: "CREDIT",
    },
    BACK: {
        en: "BACK",
        es: "ATRÁS",
        gl: "ATRÁS",
        la: "RETRO",
    },
    help0: {
        en: "Be quick",
        es: "Sé rápido",
        gl: "Sé rápido",
        la: "Festina",
    },
    help1: {
        en: "Avoid any harm",
        es: "Esquiva los ataques",
        gl: "Evita calquer dano",
        la: "Vitare omne malum",
    },
    help2: {
        en: "Get what you want",
        es: "Consigue lo que quieres",
        gl: "Consegue o que queres",
        la: "Capere quod vis",
    },
    about0: {
        en: "Made by Miguel Queiruga Portela",
        es: "Hecho por Miguel Queiruga Portela",
        gl: "Feito por Miguel Queiruga Portela",
        la: "Fecit per Miguel Queiruga Portela",
    },
    about1: {
        en: "All rights reserved",
        es: "Todos los derechos reservados",
        gl: "Todos os dereitos reservados",
        la: "Omnia jura reservata",
    },
    about2: {
        en: "MMXXIII Marín, SPAIN",
        es: "MMXXIII Marín, ESPAÑA",
        gl: "MMXXIII Marín, ESPAÑA",
        la: "MMXXIII Marín, HISPANIA",
    },
    shoot: {
        en: "shoot",
        es: "disparar",
        gl: "disparar",
        la: "jaculor",
    },
    jump: {
        en: "jump",
        es: "saltar",
        gl: "saltar",
        la: "saltare",
    },
    luck: {
        en: "luck",
        es: "suerte",
        gl: "sorte",
        la: "fortuna",
    },
    PAUSE: {
        en: "PAUSE",
        es: "PAUSA",
        gl: "PAUSA",
        la: "PAUSA",
    },
    GAMEOVER: {
        en: "GAME OVER",
        es: "FIN DEL JUEGO",
        gl: "XOGO REMATADO",
        la: "FINIS LUDUM",
    },
    OVERTIME: {
        en: "You exceeded 1 hour of gameplay",
        es: "Has excedido 1 hora de juego",
        gl: "Pasaches máis dunha hora xogando",
        la: "Horam ludendi unius excessisti",
    },
    OVERDEATH: {
        en: "You died 100 times",
        es: "Has muerto 100 veces",
        gl: "Morreches 100 veces",
        la: "Centum mortes passus es",
    },
    gameOver0: {
        en: (score) => {return `You scored ${score} point${score === "I" ? "" : "s"}`},
        es: (score) => {return `Has conseguido ${score} punto${score === "I" ? "" : "s"}`},
        gl: (score) => {return `Marcaches ${score} punto${score === "I" ? "" : "s"}`},
        la: (score) => {return `Vos laceratum ${score} punct${score === "I" ? "um" : "a"}`},
    },
    RESUME: {
        en: "RESUME",
        es: "REANUDAR",
        gl: "RETOMAR",
        la: "RESUMO",
    },
    RESTART: {
        en: "RESTART",
        es: "REINICIAR",
        gl: "REINICIAR",
        la: "LUDERE",
    },
    RESTART_CONFIRMATION: {
        en: "Are you sure?",
        es: "¿Estás seguro?",
        gl: "Estás seguro?",
        la: "Esne certus?",
    },
    START_MENU_CONFIRMATION: {
        en: "BACK TO START MENU?",
        es: "¿VOLVER AL MENÚ DE INICIO?",
        gl: "VOLTAR AO MENÚ DE INICIO?",
        la: "REDI AD MENU INITIUM?",
    },
    THE_END: {
        en: "THE END",
        es: "FIN",
        gl: "FIN",
        la: "FINIS",
    },
    SAVE_REPLAY: {
        en: "SAVE REPLAY",
        es: "GUARDAR REPETICIÓN",
        gl: "GARDAR REPETICIÓN",
        la: "REPETICIONEM CONSERVARE",
    },
    TWEET_MSG: {
        en: (deaths, atlantus, timeStr) => { return `I finished Moli with ${deaths} death${deaths === 1 ? "" : "s"} and ${atlantus} Atlantus in ${timeStr}` },
        es: (deaths, atlantus, timeStr) => { return `Acabé Moli con ${deaths} muerte${deaths === 1 ? "" : "s"} y ${atlantus} Atlantus en ${timeStr}` },
        gl: (deaths, atlantus, timeStr) => { return `Rematei Moli con ${deaths} morte${deaths === 1 ? "" : "s"} e ${atlantus} Atlantus en ${timeStr}` },
        la: (deaths, atlantus, timeStr) => { return `Moli cum ${deaths > 0 ? romanize(deaths) : "absque"} ${deaths <= 1 ? "morte" : "mortibus"} et ${romanize(atlantus)} Atlantus confeci ${timeStr}` },
    },
    SHARE: {
        en: "SHARE",
        es: "COMPARTIR",
        gl: "COMPARTIR",
        la: "AD PARTICIPES",
    },
    YES: {
        en: "YES",
        es: "SÍ",
        gl: "SÍ",
        la: "SIC",
    },
    NO: {
        en: "NO",
        es: "NO",
        gl: "NON",
        la: "NON",
    },
};